dsn: ${DSN}

log:
  level: debug
  format: text

secrets:
  cookie:
    - "qwertyuiop12asdfghjkl345xcvbm987"

session:
  cookie:
    same_site: Lax
    domain: localhost

serve:
  public:
    base_url: http://localhost:4433
    cors:
      enabled: true
      allowed_origins:
        - http://localhost:3000
      allowed_methods:
        - GET
        - POST
        - OPTIONS
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Cookie
        - Content-Type
        - Accept
      exposed_headers:
        - Content-Type
        - Set-Cookie
      allow_credentials: true
  admin:
    base_url: http://localhost:4434

identity:
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

selfservice:
  default_browser_return_url: http://localhost:3000/
  allowed_return_urls:
    - http://localhost:3000
  flows:
    login:
      ui_url: http://localhost:3000/login
    registration:
      ui_url: http://localhost:3000/register
    logout: {}
    settings:
      privileged_session_max_age: 15m
  methods:
    oidc:
      enabled: true
      config:
        providers:
          - id: google
            provider: google
            client_id: 234823242238-juje2mlfsklm6iipfdaarl4cvkv71lgn.apps.googleusercontent.com
            client_secret: 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
            scope:
              - email
              - profile
              - openid
            mapper_url: file:///etc/config/kratos/google.jsonnet


hashers:
  argon2:
    parallelism: 1
    memory: 512MB
    iterations: 2
    salt_length: 16
    key_length: 16

courier:
  smtp:
    connection_uri: smtps://stub:stub@stub.stub:465